name: "Deploy to Balena - Draft"

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
    branches:
      - master

env:
  BALENA_APP: ketil/balena-ads-b

jobs:
  build:
    name: "Deploy-to-Balena-Draft"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Deploy to Balena
        uses: balena-io/deploy-to-balena-action@master
        with:
          balena_token: ${{ secrets.BALENA_DRAFT_API_KEY }}
          fleet: ${{ env.BALENA_DRAFT_FLEET }}
          multi_dockerignore: true
